const data ={
    productData:[ 
    
    { "id": 1, "name": "Cauliflower", "price": 12, "description": "Cauliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the Brassicaceae family. It is an annual plant that reproduces by seed. Typically, only the head is eaten – the edible white flesh sometimes called - Curd", "img": "https://i.imgur.com/3Ua6Eaw.jpg" }, 
    { "id": 2, "name": "Carrot", "price": 85, "description": "The carrot is a root vegetable, most commonly observed as orange in color, though purple, black, red, white, and yellow cultivars exist, all of which are domesticated forms of the wild carrot, Daucus carota, native to Europe and Southwestern Asia", "img": "https://i.imgur.com/Vz1E0hk.jpg" },
    { "id": 3, "name": "Apple", "price": 120, "description": "An apple is an edible fruit produced by an apple tree (Malus domestica). Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus.", "img": "https://i.imgur.com/cO5kvXi.jpeg" }, 
    { "id": 4, "name": "Brocolli", "price": 80, "description": "One of broccoli’s biggest advantages is its nutrient content. It’s loaded with a wide array of vitamins, minerals, fiber and other bioactive compounds.", "img": "https://i.imgur.com/umYxFiL.jpeg" }, 
    { "id": 5, "name": "Watermelon", "price": 50, "description": "Watermelon is a sweet and refreshing low calorie summer snack. It provides hydration and also essential nutrients, including vitamins, minerals, and antioxidants.", "img": "https://i.imgur.com/Wy94Tt7.jpeg" }, 
    { "id": 6, "name": "Brinjal", "price": 30, "description": "Eggplant, aubergine or brinjal is a plant species in the nightshade family Solanaceae. Solanum melongena is grown worldwide for its edible fruit. Most commonly purple, the spongy, absorbent fruit is used in several cuisines.", "img": "https://i.imgur.com/o8rzhWO.jpeg" }, 
    { "id": 7, "name": "Strawberry", "price": 139, "description": "The garden strawberry is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries, which are cultivated worldwide for their fruit. The fruit is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness.", "img": "https://i.imgur.com/0xnhLwg.jpeg" }, 
    { "id": 8, "name": "Tomato", "price": 25, "description": "The tomato is the edible berry of the plant Solanum lycopersicum, commonly known as a tomato plant. The species originated in western South America and Central America. The Nahuatl word tomatl gave rise to the Spanish word tomate, from which the English word tomato derived", "img": "https://i.imgur.com/DGQww1V.jpeg" }, 
    { "id": 9, "name": "Potato", "price": 20, "description": "The potato is a starchy tuber of the plant Solanum tuberosum and is a root vegetable native to the Americas, with the plant itself being a perennial in the nightshade family Solanaceae.", "img": "https://i.imgur.com/dRnvRZZ.jpeg" }, 
    { "id": 10, "name": "Peas", "price": 100, "description": "The pea is most commonly the small spherical seed or the seed-pod of the pod fruit Pisum sativum. Each pod contains several peas, which can be green or yellow. Botanically, pea pods are fruit, since they contain seeds and develop from the ovary of a flower.", "img": "https://i.imgur.com/A3HYjdU.jpeg" } ]
}

export default data;
